apiVersion: v1 
kind: Deployment
metadata:
  name: nginx
  # these are replicaset labels.
  labels:
    project: roboshop
    tier: db
    component: mongodb
spec:
  replicas: 1
  selector:
    # Using these labels replicaset selects the pod.
    matchLabels:
      project: roboshop
      tier: db
      component: mongodb
  # This is pod definition,  pod is subset of replicaset
  template:
  metadata: 
    labels:
      project: roboshop
      tier: db
      component: mongodb
    spec:
      containers:
      - name: mongodb
        image: lokeshlh/mongodb:1.0.0