apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  # these are replicaset labels.
  labels:
    project: roboshop
    tier: db
    component: mongodb
spec:
  replicas: 1
  selector:
    # Using these labels replicaset selects the pod.
    matchLabels:
      project: roboshop
      tier: db
      component: mongodb
  # This is pod definition,  pod is subset of replicaset
  template:
  metadata: 
    labels:
      project: roboshop
      tier: db
      component: mongodb
    spec:
      containers:
      - name: mongodb
        image: lokeshlh/mongodb:1.0.0
---
apiVersion: v1        # its cluster service.
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mongodb
spec:
  selector:
    # Labels (resource) is used to select pods to provide network ☝️.
    project: roboshop
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 27017 # service port
    targetPort: 27017 # container port